var path = require('../../../lib/util/path.js'),
    should = require('should'),
    root = __dirname+'/';

describe('util/path',function(){
    
    describe('.normalize(path)',function(){
        [
            {
                uri:'/a/./b/../c//d\\e\\',
                result:'/a/c/d/e/'
            },
            {
                uri:'c:\\a/./b/../c//d\\e\\',
                result:'c:/a/c/d/e/'
            },
            {
                uri:'http://a.b.com/a/./b/../c//d\\e\\',
                result:'http://a.b.com/a/c/d/e/'
            },
            {
                uri:'https://a.b.com/a/./b/../c//d\\e\\',
                result:'https://a.b.com/a/c/d/e/'
            }
        ].forEach(function(config){
            it('should return '+config.result+' for '+config.uri,function(){
                path.normalize(config.uri).should.equal(config.result);
            });
        });
    });
    
    describe('.absoluteURL(url,root)',function(){
        [
            {
                uri:'http://a.b.com/c/',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/c/'
            },
            {
                uri:'./a/b',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/c/d/a/b'
            },
            {
                uri:'../a/b',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/c/a/b'
            },
            {
                uri:'/a/b',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/a/b'
            },
            {
                uri:'/a/b',
                root:'http://a.b.com/',
                result:'http://a.b.com/a/b'
            },
            {
                uri:'../../a/b',
                root:'http://a.b.com/',
                result:'http://a.b.com/a/b'
            },
            {
                uri:'a/b',
                root:'http://a.b.com:8090/',
                result:'http://a.b.com:8090/a/b'
            }
        ].forEach(function(config){
            it('should return '+config.result+' for '+config.uri+' with root '+config.root,function(){
                path.absoluteURL(config.uri,config.root).should.equal(config.result);
            });
        });
    });
    
    describe('.absolutePath(path,root)',function(){
        [
            {
                uri:'.//a/b',
                root:'/home/user/local/',
                result:'/home/user/local/a/b'
            },
            {
                uri:'/a/b',
                root:'/home/user/local/',
                result:'/a/b'
            },
            {
                uri:'../../../../../a/b',
                root:'/home/user/local/',
                result:'/a/b'
            },
            {
                uri:'a/b',
                root:'/home/user/local/',
                result:'/home/user/local/a/b'
            },
            {
                uri:'c:/a/b',
                root:'c:/user/local/',
                result:'c:/a/b'
            },
            {
                uri:'../../../../../a/b',
                root:'c:/user/local/',
                result:'c:/a/b'
            },
            {
                uri:'a/b',
                root:'c:/user/local/',
                result:'c:/user/local/a/b'
            }
        ].forEach(function(config){
            it('should return '+config.result+' for '+config.uri+' with root '+config.root,function(){
                path.absolutePath(config.uri,config.root).should.equal(config.result);
            });
        });
    });
    
    describe('.absolute(file,root)',function(){
        [
            {
                uri:'http://a.b.com/c/',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/c/'
            },
            {
                uri:'./a/b',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/c/d/a/b'
            },
            {
                uri:'../a/b',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/c/a/b'
            },
            {
                uri:'/a/b',
                root:'http://a.b.com/c/d/',
                result:'http://a.b.com/a/b'
            },
            {
                uri:'/a/b',
                root:'http://a.b.com/',
                result:'http://a.b.com/a/b'
            },
            {
                uri:'../../a/b',
                root:'http://a.b.com/',
                result:'http://a.b.com/a/b'
            },
            {
                uri:'a/b',
                root:'http://a.b.com:8090/',
                result:'http://a.b.com:8090/a/b'
            },
            {
                uri:'.//a/b',
                root:'/home/user/local/',
                result:'/home/user/local/a/b'
            },
            {
                uri:'/a/b',
                root:'/home/user/local/',
                result:'/a/b'
            },
            {
                uri:'../../../../../a/b',
                root:'/home/user/local/',
                result:'/a/b'
            },
            {
                uri:'a/b',
                root:'/home/user/local/',
                result:'/home/user/local/a/b'
            },
            {
                uri:'c:/a/b',
                root:'c:/user/local/',
                result:'c:/a/b'
            },
            {
                uri:'../../../../../a/b',
                root:'c:/user/local/',
                result:'c:/a/b'
            },
            {
                uri:'a/b',
                root:'c:/user/local/',
                result:'c:/user/local/a/b'
            }
        ].forEach(function(config){
            it('should return '+config.result+' for '+config.uri+' with root '+config.root,function(){
                path.absolute(config.uri,config.root).should.equal(config.result);
            });
        });
    });

    describe('.absoluteAltRoot(uri,pathRoot,webRoot)',function(){
        [
            {
                uri:'../../../../../a/b',
                pathRoot:'c:/user/local/',
                webRoot:'/home/user/local/',
                result:'c:/a/b'
            },
            {
                uri:'./a/b',
                pathRoot:'c:/user/local/',
                webRoot:'/home/user/local/',
                result:'c:/user/local/a/b'
            },
            {
                uri:'a/b',
                pathRoot:'c:/user/local/',
                webRoot:'/home/user/local/',
                result:'c:/user/local/a/b'
            },
            {
                uri:'/a/b',
                pathRoot:'c:/user/local/',
                webRoot:'/home/user/local/',
                result:'/home/user/local/a/b'
            }
        ].forEach(function(config){
            it('should return '+config.result+' for '+config.uri+' with pathRoot '+config.pathRoot+' and webRoot '+config.webRoot,function(){
                path.absoluteAltRoot(config.uri,config.pathRoot,config.webRoot).should.equal(config.result);
            });
        });
    });

    describe('.isURL(url)',function(){
        [
            {
                uri:'http://a.b.com/a/b',
                result:true
            },
            {
                uri:'https://a.b.com/a/b',
                result:true
            },
            {
                uri:'ftp://a.b.com/a/b',
                result:true
            },
            {
                uri:'/home/user/local/',
                result:false
            }
        ].forEach(function(config){
            it('should return '+config.result+' when url is '+config.uri,function(){
                path.isURL(config.uri).should.equal(config.result);
            });
        });
    });

    describe('.wrapURI(uri)',function(){
        [
            {
                uri:'c:/a/b/a.png',
                result:'#<c:/a/b/a.png>#'
            }
        ].forEach(function(config){
            it('should return '+config.result+' when uri is '+config.uri,function(){
                path.wrapURI(config.uri).should.equal(config.result);
            });
        });
    });

    describe('.unwrapURI(uri,func)',function(){
        [
            {
                uri:'#<c:/a/b/a.png>#',
                result:'c:/a/b/a.png'
            },
            {
                uri:'#<c:/a/b/a.png>#',
                func:function(uri){
                    return null;
                },
                result:'c:/a/b/a.png'
            },
            {
                uri:'#<c:/a/b/a.png>#',
                func:function(uri){
                    return './a.png';
                },
                result:'./a.png'
            },
            {
                uri:'#<c:/a/b/a.png># and #<c:/a/b/b.png># and #<c:/a/b/c.png>#',
                func:function(uri){
                    return uri.replace('c:/a','');
                },
                result:'/b/a.png and /b/b.png and /b/c.png'
            }
        ].forEach(function(config){
            it('should return '+config.result+' when uri is '+config.uri,function(){
                path.unwrapURI(config.uri,config.func).should.equal(config.result);
            });
        });
    });

});
