// Generated by CoffeeScript 1.9.1
define(['{pro}/tools/Vector.js'], function(vec) {
  var paddedArea;
  return paddedArea = function(padding, area) {
    var height, left, ref, ref1, top, width;
    width = area.width - padding.left - padding.right;
    height = area.height - padding.top - padding.bottom;
    if (width < 0 || height < 0) {
      console.error({
        padding: padding,
        area: area
      });
      console.error({
        width: width,
        height: height
      });
      throw "paddingArea() Error: there is no enough space for padding.";
    }
    left = ((ref = area.x) != null ? ref : area.left) + padding.left;
    top = ((ref1 = area.y) != null ? ref1 : area.top) + padding.top;
    return {
      x: left,
      y: top,
      left: left,
      top: top,
      width: width,
      height: height,
      right: left + width,
      bottom: top + height
    };
  };
});
